language: python
os: linux
dist: xenial
python:
  - "3.7"
  - "3.8"
services:
  - mysql
env:
  - DB=mysql DEBUG=f
before_script:
  - mysql -u root -e "CREATE USER 'ensembl'@'localhost' IDENTIFIED BY '';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'ensembl'@'localhost';"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='.' pytest ensembl.production.djcore.tests
